### ISSUE TITLE
Travis CI doesn't like the rgl package

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/ENMTools#157]
Travis won't check ENMTools fully because it fails to install rgl for some reason.  I don't think there's anything we can do about that; I'm just pinning this issue here so I don't forget it in the future.

At present I don't think we're even using any of the 3d plotting functionality that rgl is being loaded for, but short of building a separate no-3D version of hypervolume I don't see what we can do about it.

Anyway, I'm keeping hypervolume functionality off of the main branch until such time as this rgl issue is fixed, if it ever is.

**Comment by rdinnager** [comment]
I've solved this issue in another package before by adding this (which I got from [here](https://travis-ci.community/t/rgl-causing-build-failure-on-linux/4945/2)) to the .travis.yml:

``` yaml
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libcgal-dev libglu1-mesa-dev mesa-common-dev; fi
```
